version: "3.3"

services:
  zookeeper:
    image: garland/zookeeper
    hostname: zookeeper
    ports:
     - "2181"
#     - "2888"
#     - "3888"

  mesos-master:
    image: mesosphere/mesos-master:1.3.0
    hostname: mesos-master
    entrypoint: [ "mesos-master" ]
    ports:
      - "5050"
    links:
      - zookeeper
    environment:
      - MESOS_CLUSTER=local
      - MESOS_HOSTNAME=mesos-master.docker
      - MESOS_LOG_DIR=/var/log
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_ROLES=public
      - MESOS_ZK=zk://zookeeper:2181/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.3.0
    entrypoint:
      - mesos-slave
    privileged: true
    hostname: mesos-slave
    ports:
      - "5051"
    links:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_CONTAINERIZERS=mesos
      - MESOS_ISOLATOR=cgroups/cpu, cgroups/mem
      - MESOS_LOG_DIR=var/log
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_PORT=5051
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
      - MESOS_DOCKER_STOP_TIMEOUT=60secs
      - MESOS_RESOURCES=cpus:4;mem:1280;disk:25600;ports(*):[12000-12999]

  marathon:
    build:
      context: .
      dockerfile: Dockerfile.marathon
      args:
        - APP_VERSION=$APP_VERSION
        - MARATHON_VERSION=${MARATHON_VERSION-v1.6.352}
    ports:
      - "8080"
    links:
      - zookeeper
      - mesos-master
      - vault
    environment:
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_DECLINE_OFFER_DURATION=3600000
      - MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon
      - MARATHON_MESOS_ROLE=public
      - MARATHON_PLUGIN_DIR=/plugins
      - MARATHON_PLUGIN_CONF=/plugin-conf-test.json
      - MARATHON_ENABLE_FEATURES=secrets

  vault:
    image: vault:0.9.6
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=testroottoken
      - SKIP_SETCAP=true # suppressing Vault's IPC lock behavior which causes problems in Travis (see https://github.com/hashicorp/docker-vault/issues/24)
    ports:
      - "8200"
